import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSmart_Bank_System = new javax.swing.JLabel();
        btnCustomers = new javax.swing.JButton();
        btnfixed_deposit = new javax.swing.JButton();
        btnAccounts = new javax.swing.JButton();
        btndeposit_transactions = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        lblSmart_Bank_System.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSmart_Bank_System.setForeground(new java.awt.Color(0, 51, 51));
        lblSmart_Bank_System.setText("Smart Bank System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblSmart_Bank_System, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSmart_Bank_System)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 0, 230, 40));

        btnCustomers.setBackground(new java.awt.Color(0, 0, 0));
        btnCustomers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomers.setText("Customers");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 102, 137, -1));

        btnfixed_deposit.setBackground(new java.awt.Color(0, 0, 0));
        btnfixed_deposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnfixed_deposit.setForeground(new java.awt.Color(255, 255, 255));
        btnfixed_deposit.setText("Fixed Deposit");
        btnfixed_deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfixed_depositActionPerformed(evt);
            }
        });
        jPanel1.add(btnfixed_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 155, -1));

        btnAccounts.setBackground(new java.awt.Color(0, 0, 0));
        btnAccounts.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnAccounts.setText("Accounts");
        btnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 169, 127, -1));

        btndeposit_transactions.setBackground(new java.awt.Color(0, 0, 0));
        btndeposit_transactions.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit_transactions.setForeground(new java.awt.Color(255, 255, 255));
        btndeposit_transactions.setText("Deposit Transactions");
        btndeposit_transactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeposit_transactionsActionPerformed(evt);
            }
        });
        jPanel1.add(btndeposit_transactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 215, -1));

        btnReports.setBackground(new java.awt.Color(0, 0, 0));
        btnReports.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jPanel1.add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 108, -1));

        btnClose.setBackground(new java.awt.Color(204, 0, 0));
        btnClose.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 376, 90, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DashBoard.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        
         Customer customer = new Customer();
         customer.setVisible(true);

         this.dispose();
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountsActionPerformed
        
        Account account = new Account ();
        account.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnAccountsActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnfixed_depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfixed_depositActionPerformed
        
        Fixed_Deposit fixed_deposit = new Fixed_Deposit();
        fixed_deposit.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnfixed_depositActionPerformed

    private void btndeposit_transactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeposit_transactionsActionPerformed
       
        Deposite_Transactions deposit_transactions = new Deposite_Transactions();
        deposit_transactions.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btndeposit_transactionsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        
        try {

        Class.forName("com.mysql.cj.jdbc.Driver");

        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/fixed_deposit_system",
            "root",
            "dc12345"
);

        JasperReport jr = JasperCompileManager.compileReport(
                "src/Customer_Report_1.jrxml"
        );

        JasperPrint jp = JasperFillManager.fillReport(
                jr,
                null,
                con
        );

        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccounts;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btndeposit_transactions;
    private javax.swing.JButton btnfixed_deposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSmart_Bank_System;
    // End of variables declaration//GEN-END:variables
}