import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Fixed_Deposit extends javax.swing.JFrame {
        Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public Fixed_Deposit() {
        initComponents();
        connect();
        tableLoad();
    }

    public void connect() {

        try {

        Class.forName("com.mysql.cj.jdbc.Driver");

        con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/fixed_deposit_system",
                "root",
                "dc12345"
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e);

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void tableLoad() {

    try {

        String sql = "SELECT * FROM fixed_deposit_accounts";

        pst = con.prepareStatement(sql);

        rs = pst.executeQuery();

        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("customer_id"),
                rs.getString("deposit_type"),
                rs.getString("principal_amount"),
                rs.getString("interest_rate"),
                rs.getString("tenure_months"),
                rs.getString("start_date"),
                rs.getString("maturity_date"),
                rs.getString("maturity_amount")

            });
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e);

    }
}
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCustomer_ID = new javax.swing.JLabel();
        lblDeposit_Type = new javax.swing.JLabel();
        lnlPrinciple_Amount = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        lblTenure = new javax.swing.JLabel();
        lblStart_Date = new javax.swing.JLabel();
        lblMaturity_Date = new javax.swing.JLabel();
        lblMaturity_Amount = new javax.swing.JLabel();
        btnModify = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tCustomer_ID = new javax.swing.JTextField();
        tPrinciple_Amount = new javax.swing.JTextField();
        tInterest_Rate = new javax.swing.JTextField();
        tTenure = new javax.swing.JTextField();
        tMaturity_Amount = new javax.swing.JTextField();
        cmbDeposit_Type = new javax.swing.JComboBox<>();
        tStart_Date = new javax.swing.JTextField();
        tMaturity_Date = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Fixed Deposit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 190, 40));

        lblCustomer_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCustomer_ID.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer_ID.setText("Customer ID");
        jPanel1.add(lblCustomer_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 118, -1));

        lblDeposit_Type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDeposit_Type.setForeground(new java.awt.Color(255, 255, 255));
        lblDeposit_Type.setText("Deposit Type");
        jPanel1.add(lblDeposit_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 116, -1));

        lnlPrinciple_Amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lnlPrinciple_Amount.setForeground(new java.awt.Color(255, 255, 255));
        lnlPrinciple_Amount.setText("Principle Amount");
        jPanel1.add(lnlPrinciple_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 209, 150, -1));

        lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl.setForeground(new java.awt.Color(255, 255, 255));
        lbl.setText("Interest Rate (%)");
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 262, 150, -1));

        lblTenure.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenure.setForeground(new java.awt.Color(255, 255, 255));
        lblTenure.setText("Tenure (Months)");
        jPanel1.add(lblTenure, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 315, -1, -1));

        lblStart_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStart_Date.setForeground(new java.awt.Color(255, 255, 255));
        lblStart_Date.setText("Start Date");
        jPanel1.add(lblStart_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 368, 91, -1));

        lblMaturity_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaturity_Date.setForeground(new java.awt.Color(255, 255, 255));
        lblMaturity_Date.setText("Maturity Date");
        jPanel1.add(lblMaturity_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 421, 123, -1));

        lblMaturity_Amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaturity_Amount.setForeground(new java.awt.Color(255, 255, 255));
        lblMaturity_Amount.setText("Maturity Amount");
        jPanel1.add(lblMaturity_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 474, 150, -1));

        btnModify.setBackground(new java.awt.Color(0, 0, 153));
        btnModify.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModify.setForeground(new java.awt.Color(255, 255, 255));
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        jPanel1.add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 516, -1, -1));

        btnRemove.setBackground(new java.awt.Color(102, 102, 102));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 516, -1, -1));

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 516, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 51, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 516, -1, -1));

        tCustomer_ID.setBackground(new java.awt.Color(102, 102, 102));
        tCustomer_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tCustomer_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 98, 182, -1));

        tPrinciple_Amount.setBackground(new java.awt.Color(102, 102, 102));
        tPrinciple_Amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tPrinciple_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 204, 182, -1));

        tInterest_Rate.setBackground(new java.awt.Color(102, 102, 102));
        tInterest_Rate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tInterest_Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 257, 182, -1));

        tTenure.setBackground(new java.awt.Color(102, 102, 102));
        tTenure.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tTenure, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 310, 155, -1));

        tMaturity_Amount.setBackground(new java.awt.Color(102, 102, 102));
        tMaturity_Amount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tMaturity_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 469, 211, -1));

        cmbDeposit_Type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDeposit_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fixed Deposit", "Short Term", "Long Term" }));
        jPanel1.add(cmbDeposit_Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 151, 211, -1));

        tStart_Date.setBackground(new java.awt.Color(102, 102, 102));
        tStart_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tStart_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 363, 155, -1));

        tMaturity_Date.setBackground(new java.awt.Color(102, 102, 102));
        tMaturity_Date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tMaturity_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 416, 155, -1));

        btnAdd.setBackground(new java.awt.Color(0, 153, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 516, 84, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fixed_Deposite.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 570));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Deposit Type", "Principle Amount", "Interest rate (%)", "Tenure (Month)", "Start Date", "Maturity Date", "Maturity Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
    String customerID     =tCustomer_ID.getText().trim();
    String depositType    = cmbDeposit_Type.getSelectedItem().toString();
    String principal      = tPrinciple_Amount.getText().trim();
    String interestRate   = tInterest_Rate.getText().trim();
    String tenure         = tTenure.getText().trim();
    String startDate      = tStart_Date.getText().trim();
    String maturityDate   = tMaturity_Date.getText().trim();
    String maturityAmount = tMaturity_Amount.getText().trim();

    if (customerID.equals("") ||
        principal.equals("") ||
        interestRate.equals("") ||
        tenure.equals("") ||
        startDate.equals("YYYY-MM-DD") ||
        maturityDate.equals("YYYY-MM-DD")) {

        JOptionPane.showMessageDialog(this,
                "Please fill all fields!");
        return;
    }

    try {

        String sql =
                "INSERT INTO fixed_deposit_accounts " +
                "(customer_id, deposit_type, principal_amount, " +
                "interest_rate, tenure_months, start_date, " +
                "maturity_date, maturity_amount) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        pst = con.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(customerID));
        pst.setString(2, depositType);
        pst.setDouble(3, Double.parseDouble(principal));
        pst.setDouble(4, Double.parseDouble(interestRate));
        pst.setInt(5, Integer.parseInt(tenure));
        pst.setString(6, startDate);
        pst.setString(7, maturityDate);

        if (maturityAmount.equals("")) {
            pst.setDouble(8, 0);
        } else {
            pst.setDouble(8, Double.parseDouble(maturityAmount));
        }

        pst.executeUpdate();
        
        tableLoad();

        JOptionPane.showMessageDialog(this,
                "Fixed Deposit added successfully!");

        clearFields();

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this,
                "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        
        String customerID = tCustomer_ID.getText().trim();

    if (customerID.equals("")) {

        JOptionPane.showMessageDialog(this,
                "Please enter Customer ID to update!");

        return;
    }

    try {

        String sql =
                "UPDATE fixed_deposit_accounts SET " +
                "deposit_type=?, " +
                "principal_amount=?, " +
                "interest_rate=?, " +
                "tenure_months=?, " +
                "start_date=?, " +
                "maturity_date=?, " +
                "maturity_amount=? " +
                "WHERE customer_id=?";

        pst = con.prepareStatement(sql);

        pst.setString(1,
                cmbDeposit_Type.getSelectedItem().toString());

        pst.setDouble(2,
                Double.parseDouble(tPrinciple_Amount.getText().trim()));

        pst.setDouble(3,
                Double.parseDouble(tInterest_Rate.getText().trim()));

        pst.setInt(4,
                Integer.parseInt(tTenure.getText().trim()));

        pst.setString(5,
                tStart_Date.getText().trim());

        pst.setString(6,
                tMaturity_Date.getText().trim());

        pst.setDouble(7,
                Double.parseDouble(tMaturity_Amount.getText().trim()));

        pst.setInt(8,
                Integer.parseInt(customerID));

        int rows = pst.executeUpdate();
        
        tableLoad();

        if (rows > 0) {

            JOptionPane.showMessageDialog(this,
                    "Fixed Deposit updated successfully!");

        } else {

            JOptionPane.showMessageDialog(this,
                    "Customer ID not found!");
        }

        clearFields();

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this,
                "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        
        String customerID = tCustomer_ID.getText().trim();

    if (customerID.equals("")) {

        JOptionPane.showMessageDialog(this,
                "Please enter Customer ID to delete!");

        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {

        try {

            String sql =
                    "DELETE FROM fixed_deposit_accounts " +
                    "WHERE customer_id=?";

            pst = con.prepareStatement(sql);

            pst.setInt(1,
                    Integer.parseInt(customerID));

            int rows = pst.executeUpdate();
            
            tableLoad();

            if (rows > 0) {

                JOptionPane.showMessageDialog(this,
                        "Fixed Deposit deleted successfully!");

            } else {

                JOptionPane.showMessageDialog(this,
                        "Customer ID not found!");
            }

            clearFields();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnRemoveActionPerformed

    public void clearFields() {

    tCustomer_ID.setText("");
    tPrinciple_Amount.setText("");
    tInterest_Rate.setText("");
    tTenure.setText("");
    tStart_Date.setText("YYYY-MM-DD");
    tMaturity_Date.setText("YYYY-MM-DD");
    tMaturity_Amount.setText("");

    cmbDeposit_Type.setSelectedIndex(0);
}
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        tCustomer_ID.setText("");
        tPrinciple_Amount.setText("");
        tInterest_Rate.setText("");
        tTenure.setText("");
        tStart_Date.setText("YYYY-MM-DD");
        tMaturity_Date.setText("YYYY-MM-DD");
        tMaturity_Amount.setText("");

        cmbDeposit_Type.setSelectedIndex(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fixed_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fixed_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fixed_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fixed_Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fixed_Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbDeposit_Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCustomer_ID;
    private javax.swing.JLabel lblDeposit_Type;
    private javax.swing.JLabel lblMaturity_Amount;
    private javax.swing.JLabel lblMaturity_Date;
    private javax.swing.JLabel lblStart_Date;
    private javax.swing.JLabel lblTenure;
    private javax.swing.JLabel lnlPrinciple_Amount;
    private javax.swing.JTextField tCustomer_ID;
    private javax.swing.JTextField tInterest_Rate;
    private javax.swing.JTextField tMaturity_Amount;
    private javax.swing.JTextField tMaturity_Date;
    private javax.swing.JTextField tPrinciple_Amount;
    private javax.swing.JTextField tStart_Date;
    private javax.swing.JTextField tTenure;
    // End of variables declaration//GEN-END:variables
}
